
A Neural Network in 11 lines of Python (Part 1)
A bare bones neural network implementation to describe the inner workings of backpropagation.
Posted by iamtrask on July 12, 2015

https://iamtrask.github.io/2015/07/12/basic-python-network/
    

In [21]:
import numpy as np

In [22]:
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))


In [23]:
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T

In [24]:
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [32]:
for j in range(5000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)

In [33]:
syn0

array([[ 6.54756796,  0.83458427,  3.96193174,  4.60094847],
       [-5.05238751,  0.48120645, -6.26263011,  4.0877705 ],
       [ 2.20864211, -0.83782006, -1.40862354, -0.76198504]])

In [34]:
syn1

array([[-8.89381274],
       [-0.65917438],
       [ 9.14038429],
       [ 4.98367896]])

In [35]:
l1

array([[9.01022942e-01, 3.01997339e-01, 1.96455072e-01, 3.18214417e-01],
       [5.50081267e-02, 4.11779390e-01, 4.65866178e-04, 9.65301154e-01],
       [9.99842532e-01, 4.99189478e-01, 9.27792764e-01, 9.78936692e-01],
       [9.75962059e-01, 6.17263280e-01, 2.39095174e-02, 9.99639139e-01]])

In [36]:
l2

array([[0.00791583],
       [0.98294766],
       [0.98428863],
       [0.02010664]])

In [37]:
l2_delta

array([[-6.21644061e-05],
       [ 2.85823850e-04],
       [ 2.42968862e-04],
       [-3.96148467e-04]])

In [38]:
l1_delta

array([[ 4.93050242e-05,  8.63746466e-06, -8.96953580e-05,
        -6.72126432e-05],
       [-1.32139418e-04, -4.56339023e-05,  1.21649981e-06,
         4.77109250e-05],
       [-3.40215925e-07, -4.00381302e-05,  1.48777443e-04,
         2.49673999e-05],
       [ 8.26546288e-05,  6.16897277e-05, -8.45032935e-05,
        -7.12167591e-07]])